services:
  - type: web
    name: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    plan: standard # Upgrade for better resources
    resources:
      cpu: 1x    # Specify CPU units
      memory: 512MB  # Specify RAM allocation
